<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Employee detail</title>

    <!-- Bootstrap -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="http://getbootstrap.com/assets/css/docs.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="bs-docs-header" id="content" tabindex="-1">
    <div class="container">
        <h1>Developers SAC</h1>
        <p>
            Pequeño prototipo de aplicación web que tiene como
            finalidad registrar y evaluar a los empleados de la empresa Developers SAC
        </p>
    </div>
</div>
<div class="container bs-docs-container">
    <div class="row">
        <h1 class="page-header" id="overview">
            <a class="anchorjs-link " href="#overview" aria-label="Anchor link for: overview" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; line-height: inherit; position: absolute; margin-left: -1em; padding-right: 0.5em;">

            </a>
            Employee detail
        </h1>

        <form class="form-horizontal" method="post" action="/employee/store">
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="name">Name</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="name" aria-describedby="inputSuccess3Status" value="<?php echo $data['name'];?>">
                    <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                    <span id="inputSuccess3Status" class="sr-only">(success)</span>
                </div>
            </div>
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="email">Email</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <span class="input-group-addon">@</span>
                        <input type="text" class="form-control" name="email" aria-describedby="inputGroupSuccess2Status" value="<?php echo $data['email'];?>">
                    </div>
                    <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                    <span id="inputGroupSuccess2Status" class="sr-only">(success)</span>
                </div>
            </div>
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="phone">Phone</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="phone" aria-describedby="inputSuccess3Status" value="<?php echo $data['phone'];?>">
                    <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                    <span id="inputSuccess3Status" class="sr-only">(success)</span>
                </div>
            </div>
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="address">Address</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="address" aria-describedby="inputSuccess3Status" value="<?php echo $data['address'];?>">
                    <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                    <span id="inputSuccess3Status" class="sr-only">(success)</span>
                </div>
            </div>
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="position">Position</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="position" aria-describedby="inputSuccess3Status" value="<?php echo $data['address'];?>">
                    <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                    <span id="inputSuccess3Status" class="sr-only">(success)</span>
                </div>
            </div>
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="salary">Salary</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="salary" aria-describedby="inputSuccess3Status" value="<?php echo $data['salary'];?>">
                    <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                    <span id="inputSuccess3Status" class="sr-only">(success)</span>
                </div>
            </div>
            <div class="form-group has-success has-feedback">
                <label class="control-label col-sm-3" for="skill">Skills</label>
                <div class="col-sm-9">
                    <?php foreach ($skills as $key => $skill):?>
                        <label class="checkbox-inline">
                            <?php if($behavior == 'new'):?>
                                <input type="checkbox" name="skills[]" value="<?php echo $skill;?>"> <?php echo $skill;?>
                            <?php else:?>
                                <?php if(array_search($skill, array_column($data['skills'], 'skill')) !== false):?>
                                    <input type="checkbox" name="skills[]" value="<?php echo $skill;?>" checked="checked"> <?php echo $skill;?>
                                <?php else:?>
                                    <input type="checkbox" name="skills[]" value="<?php echo $skill;?>"> <?php echo $skill;?>
                                <?php endif;?>
                            <?php endif;?>
                        </label>
                    <?php endforeach;?>
                </div>
            </div>

            <?php if($behavior == 'new'):?>
                <div class="form-group has-success has-feedback">
                    <label class="control-label col-sm-3" for="salary"></label>
                    <div class="col-sm-9">
                        <button class="btn btn-primary" type="submit">Register Employee</button>
                    </div>
                </div>
            <?php endif;?>
        </form>
    </div>
</div>

<footer class="bs-docs-footer">
    <div class="container">
        <ul class="bs-docs-footer-links">
            <li><a href="https://github.com">GitHub</a></li>
            <li><a href="https://www.slimframework.com/">Slem</a></li>
            <li><a href="http://getbootstrap.com/">Bootstrap</a></li>
        </ul>
        <p>
            Applicacion creado con slem framework php version 3.x
        </p>
    </div>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</body>
</html>